_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 2
                - 5
                - 13
            "12": 0.19.1
            "13": linux-x86_64
augument:
    value: true
batch_size:
    value: 128
checkpoint_dir:
    value: /kaggle/working/
cls_data_dir:
    value: /kaggle/input/11785-hw-2-p-2-face-verification-spring-2025/HW2p2_S25/cls_data
epochs:
    value: 30
lr:
    value: 0.1
num_classes:
    value: 8631
test_pairs_file:
    value: /kaggle/input/11785-hw-2-p-2-face-verification-spring-2025/HW2p2_S25/test_pairs.txt
val_pairs_file:
    value: /kaggle/input/11785-hw-2-p-2-face-verification-spring-2025/HW2p2_S25/val_pairs.txt
ver_data_dir:
    value: /kaggle/input/11785-hw-2-p-2-face-verification-spring-2025/HW2p2_S25/ver_data
